[general]
import = [
    "~/.config/alacritty/themes/themes/aura.toml"
]


[window]
opacity = 0.9
blur = true

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"


[font]
normal = { family = "Fira Code Nerd Font", style = "Regular" }
bold = { family = "Fira Code Nerd Font", style = "Bold" }
italic = { family = "Fira Code Nerd Font", style = "Italic" }
bold_italic = { family = "Fira Code Nerd Font", style = "Bold Italic" }
size = 12.0

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control"
chars = "\u0003"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"

[selection]
save_to_clipboard = true

